/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedProfileSettingsRouteImport } from './routes/_protected/profile/settings'
import { Route as ProtectedProfileOverviewRouteImport } from './routes/_protected/profile/overview'
import { Route as ProtectedProfileListRouteImport } from './routes/_protected/profile/list'
import { Route as ProtectedDiscoverSurpirseMeRouteImport } from './routes/_protected/discover/surpirse-me'
import { Route as ProtectedDiscoverRecommendMeRouteImport } from './routes/_protected/discover/recommend-me'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileSettingsRoute =
  ProtectedProfileSettingsRouteImport.update({
    id: '/profile/settings',
    path: '/profile/settings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProfileOverviewRoute =
  ProtectedProfileOverviewRouteImport.update({
    id: '/profile/overview',
    path: '/profile/overview',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProfileListRoute = ProtectedProfileListRouteImport.update({
  id: '/profile/list',
  path: '/profile/list',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDiscoverSurpirseMeRoute =
  ProtectedDiscoverSurpirseMeRouteImport.update({
    id: '/discover/surpirse-me',
    path: '/discover/surpirse-me',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDiscoverRecommendMeRoute =
  ProtectedDiscoverRecommendMeRouteImport.update({
    id: '/discover/recommend-me',
    path: '/discover/recommend-me',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/discover/recommend-me': typeof ProtectedDiscoverRecommendMeRoute
  '/discover/surpirse-me': typeof ProtectedDiscoverSurpirseMeRoute
  '/profile/list': typeof ProtectedProfileListRoute
  '/profile/overview': typeof ProtectedProfileOverviewRoute
  '/profile/settings': typeof ProtectedProfileSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/discover/recommend-me': typeof ProtectedDiscoverRecommendMeRoute
  '/discover/surpirse-me': typeof ProtectedDiscoverSurpirseMeRoute
  '/profile/list': typeof ProtectedProfileListRoute
  '/profile/overview': typeof ProtectedProfileOverviewRoute
  '/profile/settings': typeof ProtectedProfileSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/discover/recommend-me': typeof ProtectedDiscoverRecommendMeRoute
  '/_protected/discover/surpirse-me': typeof ProtectedDiscoverSurpirseMeRoute
  '/_protected/profile/list': typeof ProtectedProfileListRoute
  '/_protected/profile/overview': typeof ProtectedProfileOverviewRoute
  '/_protected/profile/settings': typeof ProtectedProfileSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/sign-up'
    | '/discover/recommend-me'
    | '/discover/surpirse-me'
    | '/profile/list'
    | '/profile/overview'
    | '/profile/settings'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/sign-up'
    | '/discover/recommend-me'
    | '/discover/surpirse-me'
    | '/profile/list'
    | '/profile/overview'
    | '/profile/settings'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/login'
    | '/sign-up'
    | '/_protected/discover/recommend-me'
    | '/_protected/discover/surpirse-me'
    | '/_protected/profile/list'
    | '/_protected/profile/overview'
    | '/_protected/profile/settings'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile/settings': {
      id: '/_protected/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProtectedProfileSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile/overview': {
      id: '/_protected/profile/overview'
      path: '/profile/overview'
      fullPath: '/profile/overview'
      preLoaderRoute: typeof ProtectedProfileOverviewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile/list': {
      id: '/_protected/profile/list'
      path: '/profile/list'
      fullPath: '/profile/list'
      preLoaderRoute: typeof ProtectedProfileListRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/discover/surpirse-me': {
      id: '/_protected/discover/surpirse-me'
      path: '/discover/surpirse-me'
      fullPath: '/discover/surpirse-me'
      preLoaderRoute: typeof ProtectedDiscoverSurpirseMeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/discover/recommend-me': {
      id: '/_protected/discover/recommend-me'
      path: '/discover/recommend-me'
      fullPath: '/discover/recommend-me'
      preLoaderRoute: typeof ProtectedDiscoverRecommendMeRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDiscoverRecommendMeRoute: typeof ProtectedDiscoverRecommendMeRoute
  ProtectedDiscoverSurpirseMeRoute: typeof ProtectedDiscoverSurpirseMeRoute
  ProtectedProfileListRoute: typeof ProtectedProfileListRoute
  ProtectedProfileOverviewRoute: typeof ProtectedProfileOverviewRoute
  ProtectedProfileSettingsRoute: typeof ProtectedProfileSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDiscoverRecommendMeRoute: ProtectedDiscoverRecommendMeRoute,
  ProtectedDiscoverSurpirseMeRoute: ProtectedDiscoverSurpirseMeRoute,
  ProtectedProfileListRoute: ProtectedProfileListRoute,
  ProtectedProfileOverviewRoute: ProtectedProfileOverviewRoute,
  ProtectedProfileSettingsRoute: ProtectedProfileSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
